default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/avaliacao_holger_development.sqlite3

test:
  <<: *default
  database: db/avaliacao_holger_test.sqlite3

production:
  <<: *default
  database: db/avaliacao_holger_production.sqlite3
